"""Backlog tooling: tasks.yaml is the source of truth for tasks, sprints and status.

Commands: validate | render | status ID STATUS | sprint NAME ID,ID | report | issues | milestones
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import date
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
TASKS_FILE = ROOT / "backlog" / "tasks.yaml"
BACKLOG_MD = ROOT / "docs" / "BACKLOG.md"
SPRINT_DIR = ROOT / "docs" / "sprints"

STATUSES = ("backlog", "ready", "in_progress", "in_review", "done", "blocked")
MILESTONES = {
    "M0": "M0 Setup and spikes",
    "M1": "M1 Walking skeleton",
    "M2": "M2 Receptionist behaviour",
    "M3": "M3 Eval core",
    "M4": "M4 Review and caller-sim",
    "M5": "M5 Improvement and governance",
    "M6": "M6 Hardening and telephony",
}
REQUIRED = (
    "id",
    "title",
    "milestone",
    "type",
    "requirements",
    "description",
    "technical_approach",
    "dependencies",
    "acceptance_criteria",
    "owner",
    "estimate_h",
    "priority",
    "status",
)
ID_RE = re.compile(r"^T-M\d-\d{2}$")
REQ_RE = re.compile(r"^(FR|NFR)-\d{2}$")

Task = dict[str, Any]


def load_tasks(path: Path = TASKS_FILE) -> list[Task]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    tasks: list[Task] = data["tasks"]
    return tasks


def validate(tasks: list[Task]) -> list[str]:
    errors: list[str] = []
    ids = [t.get("id") for t in tasks]
    for dup in {i for i in ids if ids.count(i) > 1}:
        errors.append(f"duplicate id {dup}")
    known = set(ids)
    for t in tasks:
        tid = t.get("id", "<missing id>")
        for key in REQUIRED:
            if t.get(key) in (None, "", []) and key != "dependencies":
                errors.append(f"{tid}: missing field '{key}'")
        if not ID_RE.match(str(tid)):
            errors.append(f"{tid}: id must look like T-M1-03")
        if t.get("status") not in STATUSES:
            errors.append(f"{tid}: invalid status {t.get('status')!r}")
        if t.get("milestone") not in MILESTONES:
            errors.append(f"{tid}: unknown milestone {t.get('milestone')!r}")
        for dep in t.get("dependencies") or []:
            if dep not in known:
                errors.append(f"{tid}: unknown dependency {dep}")
        for req in t.get("requirements") or []:
            if not REQ_RE.match(str(req)):
                errors.append(f"{tid}: bad requirement id {req}")
        if not isinstance(t.get("estimate_h"), int | float):
            errors.append(f"{tid}: estimate_h must be a number")
    return errors


def set_field(text: str, task_id: str, field: str, value: str | int | None) -> str:
    """Rewrite one top-level field of one task block, preserving comments and layout."""
    rendered = "null" if value is None else str(value)
    block = re.compile(rf"(^- id: {re.escape(task_id)}\n(?:(?!^- id: ).*\n?)*)", re.MULTILINE)
    match = block.search(text)
    if not match:
        raise KeyError(f"task {task_id} not found")
    new_block, n = re.subn(
        rf"^(  {re.escape(field)}: ).*$",
        rf"\g<1>{rendered}",
        match.group(1),
        count=1,
        flags=re.MULTILINE,
    )
    if n == 0:
        raise KeyError(f"field {field} not found on {task_id}")
    return text[: match.start()] + new_block + text[match.end() :]


def _rewrite(task_id: str, field: str, value: str | int | None, path: Path = TASKS_FILE) -> None:
    path.write_text(set_field(path.read_text(encoding="utf-8"), task_id, field, value), "utf-8")


def render_markdown(tasks: list[Task]) -> str:
    lines = [
        "# Backlog",
        "",
        "> Generated by `make backlog-render` from `backlog/tasks.yaml`. Do not edit by hand.",
        "",
        "## Progress",
        "",
        "| Milestone | Done | In flight | Total | Est. hours (remaining) |",
        "|---|---|---|---|---|",
    ]
    for ms, name in MILESTONES.items():
        ts = [t for t in tasks if t["milestone"] == ms]
        done = sum(t["status"] == "done" for t in ts)
        live = sum(t["status"] in ("in_progress", "in_review") for t in ts)
        remaining = sum(t["estimate_h"] for t in ts if t["status"] != "done")
        lines.append(f"| {name} | {done} | {live} | {len(ts)} | {remaining} |")
    sprints = sorted({str(t["sprint"]) for t in tasks if t.get("sprint")})
    if sprints:
        lines += ["", "## Sprint backlog", ""]
        for sp in sprints:
            lines += [f"### {sp}", "", "| ID | Title | Est (h) | Status |", "|---|---|---|---|"]
            lines += [
                f"| {t['id']} | {t['title']} | {t['estimate_h']} | {t['status']} |"
                for t in tasks
                if t.get("sprint") == sp
            ]
            lines.append("")
    for ms, name in MILESTONES.items():
        ts = [t for t in tasks if t["milestone"] == ms]
        lines += [
            "",
            f"## {name}",
            "",
            "| ID | Title | Req | Deps | Est (h) | Owner | Status | Sprint | Issue |",
            "|---|---|---|---|---|---|---|---|---|",
        ]
        for t in ts:
            issue = f"#{t['issue']}" if t.get("issue") else ""
            lines.append(
                f"| {t['id']} | {t['title']} | {', '.join(t['requirements'])} | "
                f"{', '.join(t.get('dependencies') or [])} | {t['estimate_h']} | {t['owner']} | "
                f"{t['status']} | {t.get('sprint') or ''} | {issue} |"
            )
    return "\n".join(lines) + "\n"


def issue_body(t: Task) -> str:
    ac = "\n".join(f"- [ ] {a}" for a in t["acceptance_criteria"])
    deps = ", ".join(t.get("dependencies") or []) or "none"
    return (
        f"**Task:** {t['id']}  |  **Milestone:** {t['milestone']}  |  **Type:** {t['type']}\n"
        f"**Requirements:** {', '.join(t['requirements'])}\n"
        f"**Owner:** {t['owner']}  |  **Estimate:** {t['estimate_h']} h  |  "
        f"**Priority:** {t['priority']}\n\n"
        f"### Description\n{str(t['description']).strip()}\n\n"
        f"### Technical approach\n{str(t['technical_approach']).strip()}\n\n"
        f"### Dependencies\n{deps}\n\n### Acceptance criteria\n{ac}\n\n"
        f"Cursor prompt: `{t.get('prompt', 'prompts/')}`\n"
    )


def report_markdown(tasks: list[Task], title: str, git_log: dict[str, str] | None = None) -> str:
    git_log = git_log or {}
    done = [t for t in tasks if t["status"] == "done"]
    open_ = [t for t in tasks if t["status"] != "done"]
    est_done = sum(t["estimate_h"] for t in done)
    lines = [
        f"# {title}",
        "",
        f"Generated {date.today().isoformat()} - fill every TODO before merging.",
        "",
        "## Summary",
        "",
        f"- Tasks done: {len(done)} of {len(tasks)}  |  Estimated hours delivered: {est_done}",
        "- TODO: 2-3 sentence narrative of what shipped and what did not.",
        "",
        "## Delivered",
        "",
        "| Task | Title | Commits |",
        "|---|---|---|",
    ]
    lines += [f"| {t['id']} | {t['title']} | {git_log.get(t['id'], '')} |" for t in done]
    lines += [
        "",
        "## Not delivered / carried over",
        "",
        "| Task | Title | Status |",
        "|---|---|---|",
    ]
    lines += [f"| {t['id']} | {t['title']} | {t['status']} |" for t in open_]
    lines += [
        "",
        "## Metrics (TODO: paste real numbers, link run IDs)",
        "",
        "- CI status / coverage:",
        "- Latency (p50/p95) if measurable:",
        "- Eval results (run IDs):",
        "",
        "## Decisions made (link docs/DECISIONS.md entries)",
        "",
        "- TODO",
        "",
        "## Risks and blockers",
        "",
        "- TODO",
        "",
        "## Estimate vs actual",
        "",
        "- TODO: hours planned vs spent, why they differ",
        "",
        "## Next sprint",
        "",
        "- TODO",
    ]
    return "\n".join(lines) + "\n"


def _git_log_for(tasks: list[Task]) -> dict[str, str]:  # pragma: no cover - needs git history
    out: dict[str, str] = {}
    for t in tasks:
        res = subprocess.run(
            ["git", "log", "--oneline", f"--grep={t['id']}"],
            capture_output=True,
            text=True,
            cwd=ROOT,
            check=False,
        )
        out[t["id"]] = "; ".join(res.stdout.strip().splitlines()[:5])
    return out


def _create_issues(dry_run: bool) -> None:  # pragma: no cover - calls the gh CLI
    for t in load_tasks():
        if t.get("issue"):
            continue
        cmd = [
            "gh",
            "issue",
            "create",
            "--title",
            f"[{t['id']}] {t['title']}",
            "--body-file",
            "-",
            "--label",
            f"type:{t['type']}",
            "--label",
            f"prio:{t['priority']}",
            "--milestone",
            MILESTONES[t["milestone"]],
        ]
        if dry_run:
            print("DRY RUN:", " ".join(cmd))
            continue
        res = subprocess.run(cmd, input=issue_body(t), capture_output=True, text=True, check=True)
        num = res.stdout.strip().rsplit("/", 1)[-1]
        _rewrite(t["id"], "issue", int(num))
        print(f"{t['id']} -> #{num}")


def _create_milestones() -> None:  # pragma: no cover - calls the gh CLI
    for title in MILESTONES.values():
        subprocess.run(
            ["gh", "api", "repos/{owner}/{repo}/milestones", "-f", f"title={title}"],
            check=False,
        )


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="backlog")
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("validate")
    sub.add_parser("render")
    s = sub.add_parser("status")
    s.add_argument("task_id")
    s.add_argument("status", choices=STATUSES)
    sp = sub.add_parser("sprint")
    sp.add_argument("name")
    sp.add_argument("task_ids", help="comma separated")
    r = sub.add_parser("report")
    r.add_argument("--sprint")
    r.add_argument("--milestone")
    r.add_argument("--force", action="store_true")
    i = sub.add_parser("issues")
    i.add_argument("--dry-run", action="store_true")
    sub.add_parser("milestones")
    args = p.parse_args(argv)

    if args.cmd == "validate":
        errs = validate(load_tasks())
        for e in errs:
            print("ERROR:", e)
        print("backlog OK" if not errs else f"{len(errs)} problem(s)")
        return 1 if errs else 0
    if args.cmd == "render":
        BACKLOG_MD.write_text(render_markdown(load_tasks()), encoding="utf-8")
        print(f"wrote {BACKLOG_MD}")
    elif args.cmd == "status":
        _rewrite(args.task_id, "status", args.status)
    elif args.cmd == "sprint":
        for tid in args.task_ids.split(","):
            _rewrite(tid.strip(), "sprint", args.name)
    elif args.cmd == "report":
        tasks = load_tasks()
        if args.sprint:
            sel, name = (
                [t for t in tasks if t.get("sprint") == args.sprint],
                f"sprint-{args.sprint}",
            )
        elif args.milestone:
            sel, name = [t for t in tasks if t["milestone"] == args.milestone], args.milestone
        else:
            print("give --sprint or --milestone")
            return 2
        SPRINT_DIR.mkdir(parents=True, exist_ok=True)
        out = SPRINT_DIR / f"{name}-report.md"
        if out.exists() and not args.force:
            print(f"{out} exists (use --force)")
            return 1
        out.write_text(report_markdown(sel, f"Report: {name}", _git_log_for(sel)), "utf-8")
        print(f"wrote {out}")
    elif args.cmd == "issues":
        _create_issues(args.dry_run)
    elif args.cmd == "milestones":
        _create_milestones()
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
